### ISSUE TITLE
关于更新OC后的Bigsur相关疑问

### ISSUE THREAD

**Issue by wqianglxf** [zncs520/GPD-P2-MAX-Hackintosh#1]
老哥，给力呀，说来就来
有三个疑问点：
1. OC引导BigSur，P2 Max TYPE-C接口能直接连接LG 27UL850 4K显示器吗？
2. TYPE-C接口连接4K显示器后，反向充电给P2 Max也是没问题吗？
3. 蓝牙鼠标是不是要用5.0的，就可以蓝牙和WiFi同时用？
以上问题，如果你测试过，请回复一下

**Comment by zncs520** [comment]
3个肯定回答 不然你以为我是怎么一线通的

**Comment by wqianglxf** [comment]
下午尝试直接用你的EFI代替之前的Clover引导，结果无限重启，检查了以下的设置，没有问题
![image](https://user-images.githubusercontent.com/66858128/103767788-34eb9600-505c-11eb-9510-40b1de3f6cfe.png)
加了-v后发现好像驱动有问题
![image](https://user-images.githubusercontent.com/66858128/103767853-52206480-505c-11eb-8419-0d3117fa7926.png)
这是什么原因呀
