### ISSUE TITLE
此OC EFI引导时无限重启

### ISSUE THREAD

**Issue by wqianglxf** [zncs520/GPD-P2-MAX-Hackintosh#2]
从Azkali Clover 转用此OC引导后，按照教程中先执行了setup var将DVMT显存增加。
无法启动，一直重启。
PS.Clover 引导时可以Bigsur，可以连接4K显示屏，状态正常。
![image](https://user-images.githubusercontent.com/66858128/103973287-0d0a4880-51aa-11eb-9ccf-880b295968a9.png)

**Comment by zncs520** [comment]
启动界面不对,你确定是用了我的EFI ??  NVRAM 清理下

**Comment by zncs520** [comment]
> 从Clover 转用OC引导后，按照教程中先执行了setup var命令 ，将DVMT显存增加后。无法启动，一直重启。
> PS.Clover 引导时可以Bigsur，可以连接4K显示屏，状态正常。
> ![image](https://user-images.githubusercontent.com/66858128/103973287-0d0a4880-51aa-11eb-9ccf-880b295968a9.png)

确定替换了EFI分区文件?

我这 二十几台都没问题

**Comment by wqianglxf** [comment]
确定，我尝试了两种方法：
第一种方法：删除原来EFI分区中的Clover EFI引导（EFI分区中的所有文件），然后复制你的OC EFI到EFI分区。开机选择NVRAM回车。电脑重启再进行时，无法引导，失败！
第二种方法：用USB引导你的EFI，选择Nvram回车，电脑重启后，无法引导进入，相同的位置自动重启。失败！
我还有2台电脑一直OC引导使用，只有P2 Max用Clover引导。
有一个疑问，你这个OC EFI启动到OC界面时，MacOS的系统选项是 Macos Installer.

**Comment by wqianglxf** [comment]
今天各种尝试依然不行
![image](https://user-images.githubusercontent.com/66858128/104090077-13ceb380-52af-11eb-81c3-56d6e7af6945.png)

**Comment by zncs520** [comment]
> 今天各种尝试依然不行
> ![image](https://user-images.githubusercontent.com/66858128/104090077-13ceb380-52af-11eb-81c3-56d6e7af6945.png)
 OC启动界面呢?

**Comment by andot** [comment]
我怀疑是使用 Clover 安装 Bigsur 在引导上跟 OC 不兼容。我有个台式机使用的 OC 安装的 BigSur，安装之后，使用 Clover 引导时，需要选择 Preboot 分区才能成功启动。所以我估计反过来也是一样，Clover 安装之后的分区结构可能跟 OC 不一样，所以 OC 无法启动。

**Comment by wqianglxf** [comment]
> 我怀疑是使用 Clover 安装 Bigsur 在引导上跟 OC 不兼容。我有个台式机使用的 OC 安装的 BigSur，安装之后，使用 Clover 引导时，需要选择 Preboot 分区才能成功启动。所以我估计反过来也是一样，Clover 安装之后的分区结构可能跟 OC 不一样，所以 OC 无法启动。

原来是这个原因，那除了重新安装系统，还有什么办法呢？

**Comment by andot** [comment]
不知道，我最近不折腾这个小本了。我的台式机现在也换成 linux 系统了。

**Comment by wqianglxf** [comment]
@zncs520 ![image](https://user-images.githubusercontent.com/66858128/105496679-c7e12d00-5cf8-11eb-8df7-3e97d2e2948a.jpeg)
这是用您OC时的启动界面。￼最近一直在忙，今天有些时间。￼

**Comment by juniorlemos84** [comment]
你好！ 有人知道如何為Big Sur修復voodooi2c嗎？因為我同時擁有Catalina和Big Sur，並且每當opencore啟動Catalina時，觸摸屏都可以正常工作，但是當它啟動Big Sur時，觸摸屏將不再起作用。 我有Big Sur 11.3，除了觸摸屏外，其他一切都正常。 我將非常感謝您的幫助。 來自巴西的招呼🇧🇷

**Comment by andot** [comment]
@juniorlemos84 https://github.com/THEDEVIOUS1/VoodooI2CGoodix/releases/tag/v0.4.0

**Comment by juniorlemos84** [comment]
你好呀！ 
現在一切正常。
非常感謝 andot。

**Comment by wqianglxf** [comment]
> 你好呀！
> 現在一切正常。
> 非常感謝 andot。

我添加SSDT-TCSE.aml和VoodooI2CGoodix没有成功。可以分享一下你的方法吗

**Comment by juniorlemos84** [comment]
我可以做得更好，抓住我的EFI文件夹。
https://drive.google.com/drive/folders/1-vFH59IOyEnk7UaXxvF7IHPGWnWuFu7t?usp=sharing
我不是专家，如果您认为有任何错误或不必要的文件，请告诉我，以便我做得更好。

**Comment by wqianglxf** [comment]
> 我可以做得更好，抓住我的EFI文件夹。
> 
> https://drive.google.com/drive/folders/1-vFH59IOyEnk7UaXxvF7IHPGWnWuFu7t?usp=sharing
> 
> 我不是专家，如果您认为有任何错误或不必要的文件，请告诉我，以便我做得更好。

升级11.5.2后，**合盖不睡眠**。手动可以睡眠，开盖能唤醒。
